[package]
name = "passport-processing"
version = "0.1.0"
authors = ["Risto Kyötikki <risto.kyotikki@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
